#
#--- Common English String
#
text_ok=Ok
text_yes=Yes
text_no=No
text_back=Back
text_next=Next
text_about=Software
text_version=Version
text_name=Update package
text_build=Version number
text_author=Author name
text_date=Create date
text_help=Hardware
text_device=Device
text_board=Platform
text_serial=Serial number
text_recovery=Recovery version
text_quit=Quit
text_quit_msg=Do you want to quit?
text_hide=Hide
text_accept=Accept
text_install=Start
text_prepare=Preparing
text_initialize=Initializing
text_extract=Extracting
text_execute=Executing
text_log=Logs
text_log_msg=Do you want to save?
text_log_done=Copying done!
text_log_fail=Copying fail!
text_finish=Finish

#
#--- Custom English String
#
text_nv=NV